Module 05 - Machine Learning Model Development

Objective

The objective of this module is to develop, train, and compare multiple machine learning models for credit risk prediction.

The following models are implemented:

- Logistic Regression
- Decision Tree
- Random Forest
- XGBoost
- LightGBM

These models will later be compared using multiple evaluation metrics including ROC-AUC, Precision-Recall AUC, Gini Coefficient, F1 Score, Confusion Matrix and False Negative analysis.

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

from xgboost import XGBClassifier

from lightgbm import LGBMClassifier

import joblib

In [2]:
X_train = pd.read_parquet(
    "../data/processed/X_train.parquet"
)

X_test = pd.read_parquet(
    "../data/processed/X_test.parquet"
)

y_train = pd.read_parquet(
    "../data/processed/y_train.parquet"
).squeeze()

y_test = pd.read_parquet(
    "../data/processed/y_test.parquet"
).squeeze()

X_train = pd.read_parquet(
    "../data/processed/X_train.parquet"
)

X_test = pd.read_parquet(
    "../data/processed/X_test.parquet"
)

y_train = pd.read_parquet(
    "../data/processed/y_train.parquet"
).squeeze()

y_test = pd.read_parquet(
    "../data/processed/y_test.parquet"
).squeeze()

In [3]:
print("="*60)

print("Training Features :", X_train.shape)

print("Testing Features :", X_test.shape)

print("Training Labels :", y_train.shape)

print("Testing Labels :", y_test.shape)

print("="*60)

============================================================
Training Features : (1076248, 169)
Testing Features : (269062, 169)
Training Labels : (1076248,)
Testing Labels : (269062,)
============================================================

In [4]:
print("Training Distribution")

print(
    y_train.value_counts(normalize=True)
)

print()

print("Testing Distribution")

print(
    y_test.value_counts(normalize=True)
)

Training Distribution
target
0    0.800374
1    0.199626
Name: proportion, dtype: float64

Testing Distribution
target
0    0.800373
1    0.199627
Name: proportion, dtype: float64

Baseline Model 1 - Logistic Regression

Logistic Regression is trained as the baseline linear classification model. Class balancing is enabled to reduce the effect of dataset imbalance.

In [5]:
logistic_model = LogisticRegression(
    random_state=42,
    max_iter=1000,
    class_weight="balanced"
)

In [6]:
%%time

logistic_model.fit(
    X_train,
    y_train
)

print("Logistic Regression Training Completed")

Logistic Regression Training Completed
CPU times: user 18.6 s, sys: 2.08 s, total: 20.7 s
Wall time: 21.9 s

Baseline Model 2 - Decision Tree

A constrained Decision Tree is trained to provide an interpretable nonlinear baseline while minimizing overfitting.

In [7]:
decision_tree = DecisionTreeClassifier(
    random_state=42,
    max_depth=12,
    min_samples_split=100,
    min_samples_leaf=50,
    class_weight="balanced"
)

In [8]:
%%time

decision_tree.fit(
    X_train,
    y_train
)

print("Decision Tree Training Completed")

Decision Tree Training Completed
CPU times: user 57.4 s, sys: 751 ms, total: 58.1 s
Wall time: 58.3 s

Baseline Model 3 - Random Forest

Random Forest is trained as an ensemble learning algorithm capable of capturing complex nonlinear relationships among borrower and loan characteristics.

In [9]:
random_forest = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced_subsample"
)

In [10]:
%%time

random_forest.fit(
    X_train,
    y_train
)

print("Random Forest Training Completed")

Random Forest Training Completed
CPU times: user 38min 12s, sys: 40.3 s, total: 38min 53s
Wall time: 6min 32s

Advanced Model 1 - XGBoost

Extreme Gradient Boosting (XGBoost) is implemented as one of the primary gradient boosting algorithms recommended for structured tabular datasets.

In [11]:
xgb_model = XGBClassifier(

    random_state=42,

    n_estimators=200,

    learning_rate=0.1,

    max_depth=6,

    subsample=0.8,

    colsample_bytree=0.8,

    eval_metric="logloss",

    n_jobs=-1
)

In [12]:
%%time

xgb_model.fit(
    X_train,
    y_train
)

print("XGBoost Training Completed")

XGBoost Training Completed
CPU times: user 2min 49s, sys: 3.5 s, total: 2min 52s
Wall time: 37 s

Advanced Model 2 - LightGBM

LightGBM is implemented as a gradient boosting framework optimized for large-scale structured datasets and is included as a mandatory model for comparison.

In [13]:
lightgbm_model = LGBMClassifier(

    random_state=42,

    n_estimators=200,

    learning_rate=0.1,

    max_depth=6,

    class_weight="balanced"
)

In [14]:
%%time

lightgbm_model.fit(
    X_train,
    y_train
)

print("LightGBM Training Completed")

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 214847, number of negative: 861401
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.428076 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 10484
[LightGBM] [Info] Number of data points in the train set: 1076248, number of used features: 168
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LightGBM Training Completed
CPU times: user 1min 27s, sys: 4.55 s, total: 1min 32s
Wall time: 21.6 s

Trained Models

All baseline and advanced machine learning models have now been successfully trained.

The evaluation phase will compare their predictive performance using multiple business and machine learning metrics.

In [15]:
models = {

    "Logistic Regression": logistic_model,

    "Decision Tree": decision_tree,

    "Random Forest": random_forest,

    "XGBoost": xgb_model,

    "LightGBM": lightgbm_model

}

print("Models Trained Successfully")

print()

for model in models:

    print(model)

Models Trained Successfully

Logistic Regression
Decision Tree
Random Forest
XGBoost
LightGBM

Model Evaluation

All trained machine learning models are evaluated using identical performance metrics to ensure a fair comparison.

The evaluation focuses not only on prediction accuracy but also on identifying the model that minimizes credit risk by reducing false negatives.

Evaluation Metrics

- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC
- Precision-Recall AUC
- Gini Coefficient
- False Positive Rate
- False Negative Rate

In [16]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix
)

In [17]:
results = []

confusion_matrices = {}

classification_reports = {}

In [18]:
for name, model in models.items():

    predictions = model.predict(X_test)

    probabilities = model.predict_proba(X_test)[:, 1]

    tn, fp, fn, tp = confusion_matrix(
        y_test,
        predictions
    ).ravel()

    accuracy = accuracy_score(
        y_test,
        predictions
    )

    precision = precision_score(
        y_test,
        predictions
    )

    recall = recall_score(
        y_test,
        predictions
    )

    f1 = f1_score(
        y_test,
        predictions
    )

    roc_auc = roc_auc_score(
        y_test,
        probabilities
    )

    pr_auc = average_precision_score(
        y_test,
        probabilities
    )

    gini = (2 * roc_auc) - 1

    false_negative_rate = fn / (fn + tp)

    false_positive_rate = fp / (fp + tn)

    results.append({

        "Model": name,

        "Accuracy": accuracy,

        "Precision": precision,

        "Recall": recall,

        "F1 Score": f1,

        "ROC AUC": roc_auc,

        "PR AUC": pr_auc,

        "Gini": gini,

        "False Positives": fp,

        "False Negatives": fn,

        "False Positive Rate": false_positive_rate,

        "False Negative Rate": false_negative_rate

    })

    confusion_matrices[name] = confusion_matrix(
        y_test,
        predictions
    )

    classification_reports[name] = classification_report(
        y_test,
        predictions,
        output_dict=True
    )

In [19]:
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="ROC AUC",
    ascending=False
)

results_df.reset_index(
    drop=True,
    inplace=True
)

results_df

,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC,PR AUC,Gini,False Positives,False Negatives,False Positive Rate,False Negative Rate
0,XGBoost,0.920572,0.815159,0.778690,0.796507,0.962990,0.883748,0.925980,9484,11887,0.044040,0.221310
1,LightGBM,0.895054,0.673118,0.922066,0.778166,0.962805,0.882640,0.925611,24051,4186,0.111683,0.077934
2,Random Forest,0.917469,0.815312,0.758359,0.785805,0.958771,0.862784,0.917542,9227,12979,0.042847,0.241641
3,Decision Tree,0.889397,0.660791,0.916350,0.767865,0.957054,0.871033,0.914109,25266,4493,0.117325,0.083650
4,Logistic Regression,0.901398,0.695464,0.900302,0.784736,0.956656,0.853462,0.913312,21175,5355,0.098328,0.099698

In [20]:
results_df.style.format({

    "Accuracy":"{:.4f}",

    "Precision":"{:.4f}",

    "Recall":"{:.4f}",

    "F1 Score":"{:.4f}",

    "ROC AUC":"{:.4f}",

    "PR AUC":"{:.4f}",

    "Gini":"{:.4f}",

    "False Positive Rate":"{:.4f}",

    "False Negative Rate":"{:.4f}"

})

Confusion Matrices

The confusion matrix is analyzed for each model.

For credit risk prediction, minimizing False Negatives is particularly important because they represent risky borrowers incorrectly classified as safe borrowers.

In [21]:
for name, matrix in confusion_matrices.items():

    print("="*60)

    print(name)

    print("="*60)

    print(matrix)

    print()

============================================================
Logistic Regression
============================================================
[[194175  21175]
 [  5355  48357]]

============================================================
Decision Tree
============================================================
[[190084  25266]
 [  4493  49219]]

============================================================
Random Forest
============================================================
[[206123   9227]
 [ 12979  40733]]

============================================================
XGBoost
============================================================
[[205866   9484]
 [ 11887  41825]]

============================================================
LightGBM
============================================================
[[191299  24051]
 [  4186  49526]]

In [22]:
for name, report in classification_reports.items():

    print("="*60)

    print(name)

    print("="*60)

    print(pd.DataFrame(report).transpose())

    print()

============================================================
Logistic Regression
============================================================
              precision    recall  f1-score        support
0              0.973162  0.901672  0.936054  215350.000000
1              0.695464  0.900302  0.784736   53712.000000
accuracy       0.901398  0.901398  0.901398       0.901398
macro avg      0.834313  0.900987  0.860395  269062.000000
weighted avg   0.917726  0.901398  0.905847  269062.000000

============================================================
Decision Tree
============================================================
              precision    recall  f1-score        support
0              0.976909  0.882675  0.927404  215350.000000
1              0.660791  0.916350  0.767865   53712.000000
accuracy       0.889397  0.889397  0.889397       0.889397
macro avg      0.818850  0.899512  0.847635  269062.000000
weighted avg   0.913803  0.889397  0.895556  269062.000000

============================================================
Random Forest
============================================================
              precision    recall  f1-score        support
0              0.940763  0.957153  0.948887  215350.000000
1              0.815312  0.758359  0.785805   53712.000000
accuracy       0.917469  0.917469  0.917469       0.917469
macro avg      0.878037  0.857756  0.867346  269062.000000
weighted avg   0.915719  0.917469  0.916332  269062.000000

============================================================
XGBoost
============================================================
              precision    recall  f1-score        support
0              0.945411  0.955960  0.950656  215350.000000
1              0.815159  0.778690  0.796507   53712.000000
accuracy       0.920572  0.920572  0.920572       0.920572
macro avg      0.880285  0.867325  0.873582  269062.000000
weighted avg   0.919409  0.920572  0.919884  269062.000000

============================================================
LightGBM
============================================================
              precision    recall  f1-score        support
0              0.978587  0.888317  0.931269  215350.000000
1              0.673118  0.922066  0.778166   53712.000000
accuracy       0.895054  0.895054  0.895054       0.895054
macro avg      0.825852  0.905191  0.854718  269062.000000
weighted avg   0.917607  0.895054  0.900706  269062.000000

Business Interpretation

The evaluation focuses on identifying the model that provides the best balance between identifying defaulting borrowers and minimizing false alarms.

Special emphasis is placed on ROC-AUC, Precision-Recall AUC, Gini Coefficient and False Negative Rate since these metrics are more meaningful for credit risk assessment than overall accuracy alone.

In [23]:
best_model = results_df.iloc[0]["Model"]

print("Best Baseline Model")

print(best_model)

Best Baseline Model
XGBoost

In [24]:
results_df.to_csv(
    "../reports/model_comparison.csv",
    index=False
)

print("Model comparison saved successfully.")

Model comparison saved successfully.

In [25]:
results_df

,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC,PR AUC,Gini,False Positives,False Negatives,False Positive Rate,False Negative Rate
0,XGBoost,0.920572,0.815159,0.778690,0.796507,0.962990,0.883748,0.925980,9484,11887,0.044040,0.221310
1,LightGBM,0.895054,0.673118,0.922066,0.778166,0.962805,0.882640,0.925611,24051,4186,0.111683,0.077934
2,Random Forest,0.917469,0.815312,0.758359,0.785805,0.958771,0.862784,0.917542,9227,12979,0.042847,0.241641
3,Decision Tree,0.889397,0.660791,0.916350,0.767865,0.957054,0.871033,0.914109,25266,4493,0.117325,0.083650
4,Logistic Regression,0.901398,0.695464,0.900302,0.784736,0.956656,0.853462,0.913312,21175,5355,0.098328,0.099698

Baseline Model Comparison Summary

All baseline and advanced machine learning models have been evaluated.

The best-performing model identified through ROC-AUC will be selected for hyperparameter tuning in the next stage.

In [26]:
%whos

Variable                  Type                      Data/Info
-------------------------------------------------------------
DecisionTreeClassifier    ABCMeta                   <class 'sklearn.tree._cla<...>.DecisionTreeClassifier'>
LGBMClassifier            type                      <class 'lightgbm.sklearn.LGBMClassifier'>
LogisticRegression        type                      <class 'sklearn.linear_mo<...>stic.LogisticRegression'>
RandomForestClassifier    ABCMeta                   <class 'sklearn.ensemble.<...>.RandomForestClassifier'>
XGBClassifier             type                      <class 'xgboost.sklearn.XGBClassifier'>
X_test                    DataFrame                 Shape: (269062, 169)
X_train                   DataFrame                 Shape: (1076248, 169)
accuracy                  float                     0.8950539280909233
accuracy_score            function                  <function accuracy_score at 0x12ea77380>
average_precision_score   function                  <function average_precision_score at 0x12ea932e0>
best_model                str                       XGBoost
classification_report     function                  <function classification_report at 0x12ea90860>
classification_reports    dict                      n=5
confusion_matrices        dict                      n=5
confusion_matrix          function                  <function confusion_matrix at 0x12ea774c0>
decision_tree             DecisionTreeClassifier    DecisionTreeClassifier(cl<...>         random_state=42)
f1                        float                     0.7781662201761346
f1_score                  function                  <function f1_score at 0x12ea77c40>
false_negative_rate       float64                   0.07793416741137921
false_positive_rate       float64                   0.11168330624564662
fn                        int64                     4186
fp                        int64                     24051
gini                      float                     0.9256107745985627
joblib                    module                    <module 'joblib' from '/U<...>ages/joblib/__init__.py'>
lightgbm_model            LGBMClassifier            LGBMClassifier(class_weig<...>         random_state=42)
logistic_model            LogisticRegression        LogisticRegression(class_<...>er=1000, random_state=42)
matrix                    ndarray                   2x2: 4 elems, type `int64`, 32 bytes
model                     LGBMClassifier            LGBMClassifier(class_weig<...>         random_state=42)
models                    dict                      n=5
name                      str                       LightGBM
np                        module                    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
pd                        module                    <module 'pandas' from '/U<...>ages/pandas/__init__.py'>
pr_auc                    float                     0.8826400003533585
precision                 float                     0.6731179580575452
precision_score           function                  <function precision_score at 0x12ea904a0>
predictions               ndarray                   269062: 269062 elems, type `int64`, 2152496 bytes (2.0527801513671875 Mb)
probabilities             ndarray                   269062: 269062 elems, type `float64`, 2152496 bytes (2.0527801513671875 Mb)
random_forest             RandomForestClassifier    RandomForestClassifier(cl<...>jobs=-1, random_state=42)
recall                    float                     0.9220658325886207
recall_score              function                  <function recall_score at 0x12ea905e0>
report                    dict                      n=5
results                   list                      n=5
results_df                DataFrame                 Shape: (5, 12)
roc_auc                   float                     0.9628053872992813
roc_auc_score             function                  <function roc_auc_score at 0x12ea93600>
tn                        int64                     191299
tp                        int64                     49526
warnings                  module                    <module 'warnings' from '<...>/python3.12/warnings.py'>
xgb_model                 XGBClassifier             XGBClassifier(base_score=<...>ne, random_state=42, ...)
y_test                    Series                    Shape: (269062,)
y_train                   Series                    Shape: (1076248,)

In [27]:
import joblib
from pathlib import Path

# Create models directory
Path("../models").mkdir(parents=True, exist_ok=True)

# Save trained XGBoost model
joblib.dump(
    xgb_model,
    "../models/xgboost_credit_risk.pkl"
)

# Save feature names
joblib.dump(
    list(X_train.columns),
    "../models/feature_columns.pkl"
)

print("✅ XGBoost model saved successfully!")
print("✅ Feature columns saved successfully!")

✅ XGBoost model saved successfully!
✅ Feature columns saved successfully!

In [28]:
import os

print(os.listdir("../models"))

['feature_columns.pkl', '.gitkeep', 'xgboost_credit_risk.pkl']

In [29]:
X_train.columns.to_series().to_csv("../reports/feature_list.csv", index=False)